# Generated by Django 4.2.4 on 2023-09-02 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 9, 2, 15, 51, 55, 706100, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='set',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 9, 2, 15, 52, 16, 595706, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
