# Generated by Django 4.2.4 on 2023-09-03 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_group_slug_set_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='set',
            options={'verbose_name': 'набор', 'verbose_name_plural': 'Наборы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(max_length=100, verbose_name='ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_right',
            field=models.BooleanField(verbose_name='правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question', verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='group',
            name='desc',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.group', verbose_name='название теста'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='вопрос'),
        ),
        migrations.AlterField(
            model_name='set',
            name='desc',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='set',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
    ]
